services:
  vault:
    image: hashicorp/vault:1.17
    container_name: vault-lab
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    volumes:
      - ./data:/vault/data
      - ./config.hcl:/vault/config/config.hcl
    command: vault server -config=/vault/config/config.hcl
    


    
      
